In [3]:
import pandas as pd
import numpy as np

# Modeling
import lightgbm as lgb

# Evaluation of the model
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

MAX_EVALS = 2
N_FOLDS = 2

In [7]:
features1 = pd.read_csv('https://media.githubusercontent.com/media/YUN-CHIEN-LO/4th-ML100Days/master/datas/application_train.csv')

In [12]:
features1['TARGET']

0     1
1     0
2     0
3     0
4     0
     ..
81    1
82    0
83    0
84    0
85    0
Name: TARGET, Length: 86, dtype: int64

In [15]:
np.array(features1['TARGET'].astype(np.int32))

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int32)

In [34]:
np.array(features1['TARGET'].astype(np.int32)).reshape((-1,1))

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [5]:
# Read in data and separate into training and testing sets
features = pd.read_csv('https://media.githubusercontent.com/media/YUN-CHIEN-LO/4th-ML100Days/master/datas/application_train.csv')

# Extract the labels and format properly
labels = np.array(features['TARGET'].astype(np.int32)).reshape((-1,))

# Drop the unneeded columns
features = features.drop(columns = ['SK_ID_CURR', 'TARGET'])

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2)

print('Train shape: ', train_features.shape)
print('Test shape: ', test_features.shape)

train_features.head()

Train shape:  (68, 11)
Test shape:  (18, 11)


NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
34         Cash loans           F            N               Y             0   
72         Cash loans           M            N               Y             2   
24         Cash loans           M            Y               N             2   
61         Cash loans           M            N               N             0   
79         Cash loans           F            N               Y             0   

   WEEKDAY_APPR_PROCESS_START  AMT_INCOME_TOTAL  AMT_CREDIT  \
34                     FRIDAY  AMT_INCOME_TOTAL   1125000.0   
72                     FRIDAY  AMT_INCOME_TOTAL    495351.0   
24                   THURSDAY  AMT_INCOME_TOTAL    247500.0   
61                    TUESDAY  AMT_INCOME_TOTAL   1080000.0   
79                   THURSDAY  AMT_INCOME_TOTAL    113760.0   

    REGION_POPULATION_RELATIVE  DAYS_BIRTH  LIVINGAREA_MEDI  
34                    0.019689      -15997           0.0648  
72                    0.024610      -14860           0.0112  
24                    0.026392      -11286           0.1239  
61                    0.010006       -7907           0.0929  
79                    0.030755      -22935           0.1678

In [60]:
train_features.columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'CNT_CHILDREN', 'WEEKDAY_APPR_PROCESS_START', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH',
       'LIVINGAREA_MEDI'],
      dtype='object')

In [61]:
test_features.columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'CNT_CHILDREN', 'WEEKDAY_APPR_PROCESS_START', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH',
       'LIVINGAREA_MEDI'],
      dtype='object')

In [6]:
model = lgb.LGBMClassifier(random_state=50)
model

LGBMClassifier(random_state=50)

In [35]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.shape
(3, 4)

(3, 4)

In [37]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
z.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
z.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [50]:
z.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [62]:
one_hot_train = pd.get_dummies(train_features)
one_hot_test = pd.get_dummies(test_features)

In [67]:
one_hot_train.columns

Index(['CNT_CHILDREN', 'AMT_CREDIT', 'REGION_POPULATION_RELATIVE',
       'DAYS_BIRTH', 'LIVINGAREA_MEDI', 'NAME_CONTRACT_TYPE_Cash loans',
       'NAME_CONTRACT_TYPE_Revolving loans', 'CODE_GENDER_F', 'CODE_GENDER_M',
       'FLAG_OWN_CAR_N', 'FLAG_OWN_CAR_Y', 'FLAG_OWN_REALTY_N',
       'FLAG_OWN_REALTY_Y', 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
       'WEEKDAY_APPR_PROCESS_START_MONDAY',
       'WEEKDAY_APPR_PROCESS_START_SATURDAY',
       'WEEKDAY_APPR_PROCESS_START_SUNDAY',
       'WEEKDAY_APPR_PROCESS_START_THURSDAY',
       'WEEKDAY_APPR_PROCESS_START_TUESDAY',
       'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
       'AMT_INCOME_TOTAL_AMT_INCOME_TOTAL'],
      dtype='object')

In [68]:
one_hot_test.columns

Index(['CNT_CHILDREN', 'AMT_CREDIT', 'REGION_POPULATION_RELATIVE',
       'DAYS_BIRTH', 'LIVINGAREA_MEDI', 'NAME_CONTRACT_TYPE_Cash loans',
       'NAME_CONTRACT_TYPE_Revolving loans', 'CODE_GENDER_F', 'CODE_GENDER_M',
       'FLAG_OWN_CAR_N', 'FLAG_OWN_CAR_Y', 'FLAG_OWN_REALTY_N',
       'FLAG_OWN_REALTY_Y', 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
       'WEEKDAY_APPR_PROCESS_START_MONDAY',
       'WEEKDAY_APPR_PROCESS_START_SATURDAY',
       'WEEKDAY_APPR_PROCESS_START_THURSDAY',
       'WEEKDAY_APPR_PROCESS_START_TUESDAY',
       'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
       'AMT_INCOME_TOTAL_AMT_INCOME_TOTAL'],
      dtype='object')

In [69]:
one_hot_train = pd.get_dummies(train_features)
one_hot_test = pd.get_dummies(test_features)

one_hot_train, one_hot_test = one_hot_train.align(one_hot_test, axis = 1, join = 'inner')
one_hot_features = list(one_hot_train.columns)

print('Number of features: ', one_hot_train.shape[1])

Number of features:  20


In [71]:
one_hot_train.shape

(68, 20)

In [80]:
one_hot_train.head()

CNT_CHILDREN  AMT_CREDIT  REGION_POPULATION_RELATIVE  DAYS_BIRTH  \
34             0   1125000.0                    0.019689      -15997   
72             2    495351.0                    0.024610      -14860   
24             2    247500.0                    0.026392      -11286   
61             0   1080000.0                    0.010006       -7907   
79             0    113760.0                    0.030755      -22935   

    LIVINGAREA_MEDI  NAME_CONTRACT_TYPE_Cash loans  \
34           0.0648                              1   
72           0.0112                              1   
24           0.1239                              1   
61           0.0929                              1   
79           0.1678                              1   

    NAME_CONTRACT_TYPE_Revolving loans  CODE_GENDER_F  CODE_GENDER_M  \
34                                   0              1              0   
72                                   0              0              1   
24                                   0              0              1   
61                                   0              0              1   
79                                   0              1              0   

    FLAG_OWN_CAR_N  FLAG_OWN_CAR_Y  FLAG_OWN_REALTY_N  FLAG_OWN_REALTY_Y  \
34               1               0                  0                  1   
72               1               0                  0                  1   
24               0               1                  1                  0   
61               1               0                  1                  0   
79               1               0                  0                  1   

    WEEKDAY_APPR_PROCESS_START_FRIDAY  WEEKDAY_APPR_PROCESS_START_MONDAY  \
34                                  1                                  0   
72                                  1                                  0   
24                                  0                                  0   
61                                  0                                  0   
79                                  0                                  0   

    WEEKDAY_APPR_PROCESS_START_SATURDAY  WEEKDAY_APPR_PROCESS_START_THURSDAY  \
34                                    0                                    0   
72                                    0                                    0   
24                                    0                                    1   
61                                    0                                    0   
79                                    0                                    1   

    WEEKDAY_APPR_PROCESS_START_TUESDAY  WEEKDAY_APPR_PROCESS_START_WEDNESDAY  \
34                                   0                                     0   
72                                   0                                     0   
24                                   0                                     0   
61                                   1                                     0   
79                                   0                                     0   

    AMT_INCOME_TOTAL_AMT_INCOME_TOTAL  
34                                  1  
72                                  1  
24                                  1  
61                                  1  
79                                  1

In [73]:
df = pd.DataFrame(
...     [[1, 2, 3, 4], [6, 7, 8, 9]], columns=["D", "B", "E", "A"], index=[1, 2]
... )
>>> other = pd.DataFrame(
...     [[10, 20, 30, 40], [60, 70, 80, 90], [600, 700, 800, 900]],
...     columns=["A", "B", "C", "D"],
...     index=[2, 3, 4],)

In [74]:
left, right = df.align(other, join="inner", axis=1)

In [75]:
left

D  B  A
1  1  2  4
2  6  7  9

In [76]:
right

D    B    A
2   40   20   10
3   90   70   60
4  900  700  600

In [77]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from timeit import default_timer as timer

start = timer()
cv = cross_val_score(estimator = model, X = one_hot_train, 
                     y = train_labels, 
                     verbose = 2, n_jobs = -1, 
                     cv = N_FOLDS, scoring = 'roc_auc')
cv_time = timer() - start

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:    1.1s finished


In [78]:
print('Baseline model {} fold cv AUC ROC score: {:.5f}'.format(N_FOLDS, np.mean(cv)))
print('Baseline model eval time: {:.2f} seconds.'.format(cv_time))

Baseline model 2 fold cv AUC ROC score: 0.50000
Baseline model eval time: 1.11 seconds.


In [81]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le_train = train_features.copy()
le_test = test_features.copy()

In [83]:
le_train

NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
34         Cash loans           F            N               Y             0   
72         Cash loans           M            N               Y             2   
24         Cash loans           M            Y               N             2   
61         Cash loans           M            N               N             0   
79         Cash loans           F            N               Y             0   
..                ...         ...          ...             ...           ...   
57    Revolving loans           M            N               Y             0   
56         Cash loans           F            N               N             0   
75         Cash loans           F            N               Y             1   
6          Cash loans           F            Y               Y             1   
65         Cash loans           M            N               Y             0   

   WEEKDAY_APPR_PROCESS_START  AMT_INCOME_TOTAL  AMT_CREDIT  \
34                     FRIDAY  AMT_INCOME_TOTAL   1125000.0   
72                     FRIDAY  AMT_INCOME_TOTAL    495351.0   
24                   THURSDAY  AMT_INCOME_TOTAL    247500.0   
61                    TUESDAY  AMT_INCOME_TOTAL   1080000.0   
79                   THURSDAY  AMT_INCOME_TOTAL    113760.0   
..                        ...               ...         ...   
57                  WEDNESDAY  AMT_INCOME_TOTAL    247500.0   
56                     MONDAY  AMT_INCOME_TOTAL    298728.0   
75                     FRIDAY  AMT_INCOME_TOTAL   1288350.0   
6                      SUNDAY  AMT_INCOME_TOTAL   1560726.0   
65                  WEDNESDAY  AMT_INCOME_TOTAL   1256400.0   

    REGION_POPULATION_RELATIVE  DAYS_BIRTH  LIVINGAREA_MEDI  
34                    0.019689      -15997           0.0648  
72                    0.024610      -14860           0.0112  
24                    0.026392      -11286           0.1239  
61                    0.010006       -7907           0.0929  
79                    0.030755      -22935           0.1678  
..                         ...         ...              ...  
57                    0.031329      -18248           0.1198  
56                    0.019101      -21621              NaN  
75                    0.003069      -17542              NaN  
6                     0.035792      -13778              NaN  
65                    0.072508      -12049           0.1392  

[68 rows x 11 columns]

In [84]:
cat_features = []

for i, col in enumerate(le_train):
    if le_train[col].dtype == 'object':
        le_train[col] = le.fit_transform(np.array(le_train[col].astype(str)).reshape((-1, )))
        le_test[col] = le.transform(np.array(le_test[col].astype(str)).reshape((-1, )))
        cat_features.append(i)
        
print('Number of features: ', le_train.shape[1])

Number of features:  11


In [87]:
le_train.columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'CNT_CHILDREN', 'WEEKDAY_APPR_PROCESS_START', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH',
       'LIVINGAREA_MEDI'],
      dtype='object')

In [91]:
train_labels.shape

(68,)

[CV] END .................................................... total time=   0.0s
[CV] END .................................................... total time=   0.0s


In [88]:
start = timer()
cv = cross_val_score(estimator = model, X = le_train, y = train_labels, 
                     fit_params = {'categorical_feature': cat_features},
                     verbose = 2, n_jobs = -1, cv = N_FOLDS, 
                     scoring = 'roc_auc')
cv_time = timer() - start

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
/opt/homebrew/Caskroom/miniforge/base/envs/my_env/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
/opt/homebrew/Caskroom/miniforge/base/envs/my_env/lib/python3.9/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:    1.0s finished


In [89]:
print('Baseline model with label encoding {} fold cv AUC ROC score: {:.5f}'.format(N_FOLDS, np.mean(cv)))
print('Baseline model with label encoding eval time: {:.2f} seconds.'.format(cv_time))

Baseline model with label encoding 2 fold cv AUC ROC score: 0.50000
Baseline model with label encoding eval time: 0.96 seconds.


In [92]:
import random

In [100]:
list(np.logspace(np.log(0.005), np.log(0.2), base = np.exp(1), num = 1000))

[0.005000000000000004,
 0.005018496989847007,
 0.005037062407420691,
 0.005055696505862444,
 0.005074399539250138,
 0.005093171762601568,
 0.005112013431877946,
 0.005130924803987385,
 0.005149906136788399,
 0.005168957689093439,
 0.005188079720672389,
 0.005207272492256134,
 0.005226536265540098,
 0.005245871303187837,
 0.005265277868834588,
 0.005284756227090885,
 0.005304306643546163,
 0.005323929384772373,
 0.0053436247183276326,
 0.005363392912759854,
 0.0053832342376104155,
 0.00540314896341784,
 0.005423137361721474,
 0.005443199705065208,
 0.005463336267001169,
 0.0054835473220934666,
 0.005503833145921932,
 0.005524194015085871,
 0.005544630207207856,
 0.005565142000937479,
 0.005585729675955174,
 0.005606393512976024,
 0.005627133793753585,
 0.005647950801083743,
 0.005668844818808548,
 0.005689816131820096,
 0.00571086502606441,
 0.0057319917885453545,
 0.005753196707328522,
 0.005774480071545175,
 0.005795842171396196,
 0.00581728329815602,
 0.005838803744176648,
 0.0058604

In [ ]:
# Hyperparameter grid
param_grid = {
    'class_weight': [None, 'balanced'],
    'boosting_type': ['gbdt', 'goss', 'dart'],
    'num_leaves': list(range(30, 150)),
    'learning_rate': list(np.logspace(np.log(0.005), np.log(0.2), base = np.exp(1), num = 1000)),
    'subsample_for_bin': list(range(20000, 300000, 20000)),
    'min_child_samples': list(range(20, 500, 5)),
    'reg_alpha': list(np.linspace(0, 1)),
    'reg_lambda': list(np.linspace(0, 1)),
    'colsample_bytree': list(np.linspace(0.6, 1, 10)),
    'encoding': ['one_hot', 'label']
}

# Subsampling (only applicable with 'goss')
subsample_dist = list(np.linspace(0.5, 1, 100))